### ISSUE TITLE
[feat] Reentrancy Guard

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/piltover#2]
Implement a reentrency guard for the Appchain contract.

#### References
https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/security/reentrancyguard.cairo

**Comment by Akashneelesh** [comment]
Heyy @drspacemn may I take this one.

**Comment by estheroche** [comment]
i am iinterested in this , please can you assign to me?

**Comment by glihm** [comment]
> i am iinterested in this , please can you assign to me?

Hey! Thank you for considering contributing.
A PR is already open for that I'm sorry we forgot to actualise the issue assignment.

Don't hesitate to pick an other one, thank you!

**Comment by estheroche** [comment]
its fine. thank you
