### ISSUE TITLE
[feat] add config.cairo etc file

### ISSUE THREAD

**Issue by suiwater** [keep-starknet-strange/piltover#26]
#### [References OpenZeppelin](https://github.com/OpenZeppelin/cairo-contracts/tree/main/src)
update lib.cairo and add config.cairo etc.
If that's okay, I'll modify this.

**Comment by Xaxxoo** [comment]
@suiwater I am interested in this please.

**Comment by Xaxxoo** [comment]
hi @suiwater can I work on this please?

**Comment by glihm** [comment]
@suiwater the one `lib.cairo` is a good way to centralize how dependencies are exposed/used. I'll close this one but something that can be done is bumping the edition. :)
