### ISSUE TITLE
[feat] Fact Verification

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/piltover#3]
Once Herodotus Verifier implements a fact registry implement the logic for verifying the Proving Fact sent in updateState and correlating logic.

Can mock or hardcode the information if blocked on the Herodotus Fact Registry

### References
https://github.com/starkware-libs/cairo-lang/blob/ab6d079f0265f903630aac9287e93d9e7cfb6fcf/src/starkware/starknet/solidity/Starknet.sol#L303

Test state-diff pre-kzg:
https://github.com/keep-starknet-strange/snos/blob/main/tests/common/data/os_output.json

**Comment by psychiller** [comment]
I can take this up, is there some spec, I can take a look at for implementing this.

**Comment by thomas192** [comment]
Hey, I'd like to work on this.
