### ISSUE TITLE
[dev] Update to the latest starknet-rs version

### ISSUE THREAD

**Issue by akhercha** [keep-starknet-strange/piltover#31]
We want to update to the latest starknet-rs version and replace our different `FieldElement` (from `starknet_ff` / `starknet_core` ...) usages by the new `Felt` type.

This will allow us to use the AppchainCoreContract in [madara-orchestrator](https://github.com/karnotxyz/madara-orchestrator).

**Comment by od-hunter** [comment]
Can I be assigned this please?

**Comment by od-hunter** [comment]
Hello, just looked at this issue well and I realized it will take a lot of research and time, pending I have other issues I’m working on and I don’t want to disappoint you, Kindly assign this issue to someone else thank you. Sorry please🙏🏾

**Comment by drspacemn** [comment]
Feel free to take your time here.

**Comment by glihm** [comment]
Last week support for starknet `0.11.0` was added to cainome, which should unlock the bindings part of pullover: https://github.com/cartridge-gg/cainome/releases/tag/v0.3.0.

**Comment by akhercha** [comment]
Gm, sorry for the misunderstanding, this issue does not belong in this repository but in [Zaun](https://github.com/keep-starknet-strange/zaun) (makes sense as we don't have any rust code here...).

I'll close this issue - the new one is here if you're interested @od-hunter:
https://github.com/keep-starknet-strange/zaun/issues/23

**Comment by od-hunter** [comment]
GM ser @akhercha , I apologize I’m just seeing this? I’ll and comment on the issue now.
