### ISSUE TITLE
[bug] There is no implementation of l1ToL2Messages() and l2ToL1Messages()

### ISSUE THREAD

**Issue by byteZorvin** [keep-starknet-strange/piltover#33]
- Referring to the [solidity verstion](https://github.com/starkware-libs/cairo-lang/blob/v0.13.1/src/starkware/starknet/solidity/StarknetMessaging.sol#L47) of the Messaging, there is no implementation of `l1Tol2Messages()` and `l2tol1Messages()` . 
- Without these functions there is no way to check the status(failure/success) of a message whether they are consumed or yet pending.

**Comment by byteZorvin** [comment]
Please this issue to me

**Comment by glihm** [comment]
Thanks for noting this missing function, all yours!

**Comment by glihm** [comment]
Closed in #34.
