### ISSUE TITLE
[dev] `MessageHash` and `Nonce` to be public types

### ISSUE THREAD

**Issue by byteZorvin** [keep-starknet-strange/piltover#37]
- It would be great if piltover exposes the `MessageHash` and `Nonce` types as public. This would enable better readability and context for codebases building on top of piltover like Bridges.

- It could also make sense to keep them in a separate file like `types.cairo` (not sure if this is valid)

**Comment by byteZorvin** [comment]
@glihm I would like to take this up, if you allow

**Comment by glihm** [comment]
Closed by #34.
