### ISSUE TITLE
[bug] Using bindings as a depency fails to compile.

### ISSUE THREAD

**Issue by matzayonc** [keep-starknet-strange/piltover#39]
**ver: ff8853fde770fac31ea071892242e12cd386a3f1** 

After adding as a dependency

`piltover_bindings = { package = "bindings", git = "https://github.com/keep-starknet-strange/piltover.git", rev = "ff8853fde770fac31ea071892242e12cd386a3f1" }`

The whole program failes to compile.

```
3 | / abigen!(
4 | |     AppChain,
5 | |     "../target/dev/piltover_appchain.contract_class.json",
6 | |     output_path("src/bindings.rs")
7 | | );
  | |_^
```
**How to reproduce:**
Add a dependency to any program

**Proposed solution**
Include compiled `json` in this repository

**Comment by glihm** [comment]
Should be solved in #32 with cainome being bumped. Don't hesitate to re-open if necessary.
