### ISSUE TITLE
[feat] State Update Events

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/piltover#4]
Implement and test the State Update Events.

Can mock or hard code a successful state update for the time being.

#### References
https://github.com/starkware-libs/cairo-lang/blob/ab6d079f0265f903630aac9287e93d9e7cfb6fcf/src/starkware/starknet/solidity/Starknet.sol#L216

https://github.com/starkware-libs/cairo-lang/blob/ab6d079f0265f903630aac9287e93d9e7cfb6fcf/src/starkware/starknet/solidity/Starknet.sol#L248

**Comment by OkoliEvans** [comment]
I will love to try this

**Comment by AryanGodara** [comment]
Hi, I'd like to work on this issue! Could you please point me in the right direction to get started; like the first step, and I'll build up from there

**Comment by glihm** [comment]
> Hi, I'd like to work on this issue! Could you please point me in the right direction to get started; like the first step, and I'll build up from there

Hey @AryanGodara! Thank you for considering contributing.

Currently there's no component for the state. So in this issue you may add the missing event that is linked in the issue description into the app chain contract itself.

Does it make sense to you?

**Comment by TAdev0** [comment]
Hi @glihm  @drspacemn  , any update about this issue? Is anyone working on it? I can do it today if it is available :)

**Comment by thomas192** [comment]
Hello, I have been working on this with no intention to make a PR initially but it turns out I could make one soon.
