### ISSUE TITLE
[feat] Check Config Hash

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/piltover#5]
Add checks for the config hash as well as the corresponding event.

#### References
https://github.com/starkware-libs/cairo-lang/blob/ab6d079f0265f903630aac9287e93d9e7cfb6fcf/src/starkware/starknet/solidity/Starknet.sol#L73

**Comment by AkankshaAttavar** [comment]
I can take this

**Comment by OkoliEvans** [comment]
I'd like to work on this if possible

**Comment by glihm** [comment]
Will assign to @OkoliEvans if you don't mind @AkankshaAttavar. 👍
@OkoliEvans don't hesitate if you have questions.

**Comment by AkankshaAttavar** [comment]
Sure!!

**Comment by OkoliEvans** [comment]
I'm sorry @glihm but I have to drop this task. I am currently in a ZK masterclass that requires almost all my attention now. Really sorry for this, and I will definitely discuss with you once things slow down. Thank you very much
