### ISSUE TITLE
[feat] ProgramHashChanged Event

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/piltover#6]
Implement the ProgramHashChanged event.

#### References
https://github.com/starkware-libs/cairo-lang/blob/ab6d079f0265f903630aac9287e93d9e7cfb6fcf/src/starkware/starknet/solidity/Starknet.sol#L68

**Comment by Akashneelesh** [comment]
Heyy @drspacemn  I have addressed this issue in the PR #13

**Comment by thomas192** [comment]
Hello, I implemented the ProgramHashChanged event you were talking about in PR #13 since I needed it to address issue #5
