### ISSUE TITLE
[feat] update_state args

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/piltover#8]
Change the `update_state` interface and appchain implementation to accept `onchainDataHash` + `onchainDataHash`

(add tests)

#### References
https://github.com/starkware-libs/cairo-lang/blob/ab6d079f0265f903630aac9287e93d9e7cfb6fcf/src/starkware/starknet/solidity/Starknet.sol#L288

**Comment by AkankshaAttavar** [comment]
I can take this

**Comment by glihm** [comment]
> I can take this

Assigned and thank you for the work already started. 👍
