### ISSUE TITLE
[feat] Multiple Operators

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/piltover#9]
Allow multiple operators of the Core Contract via a LegacyMap.

(add tests)

#### References
https://github.com/starkware-libs/cairo-lang/blob/ab6d079f0265f903630aac9287e93d9e7cfb6fcf/src/starkware/starknet/solidity/StarknetOperator.sol#L10

**Comment by TAdev0** [comment]
Hey @drspacemn  , 
may I work on this issue?

**Comment by glihm** [comment]
> Hey @drspacemn  , 
> 
> may I work on this issue?

Hello! For sure thank you for contributing! Don't hesitate if you have any question.
